<?php
/**
 * Created by PhpStorm.
 * User: M
 * Date: 17/7/5
 * Time: 下午5:21
 */

namespace app\controllers;

use Yii;
use yii\web\Response;
use app\components\helpers\ApiHelper;

/**
 * Class ApiController
 * @package app\controllers
 */
class ApiController extends \yii\web\Controller
{
    /**
     * CSRF
     * @var bool
     */
    public $enableCsrfValidation = false;

    /**
     * 返回数据
     * @var array
     */
    public $data;

    /**
     * 用户ID
     * @var int
     */
    public $userId;

    /**
     * @param $action
     * @return bool|null
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $apiHelper = new ApiHelper();
        $apiHelper->route = $this->module->requestedRoute;
        $authResult = $apiHelper->authenticated();
        $this->data = $apiHelper->data;
        if($authResult === true){
            $this->userId = $apiHelper->userId;
        }else{
            Yii::$app->response->data = $this->data;
            return null;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @param \yii\base\Action $action
     * @param mixed $result
     * @return array|mixed
     */
    public function afterAction($action, $result)
    {
        return $this->data;
    }
}
