<?php
/**
 * Created by PhpStorm.
 * User: M
 * Date: 17/7/5
 * Time: 下午5:21
 */

namespace app\controllers;

use Yii;
use yii\web\Response;
use yii\helpers\ArrayHelper;
use app\components\helpers\ScHelper;

class Controller extends \yii\web\Controller
{
    const API_CODE_SUCCESS = 10000;
    const API_CODE_FAILURE = 30001;
    const API_CODE_SUCCESS_MSG = '请求成功';
    const API_CODE_FAILURE_MSG = '请求失败';
    const API_SIGN_KEY = 'malyan.cn';
    const CACHE_USER_LOGIN_KEY = 'user.login.';
    const IMAGE_DOMAIN = 'http://img.malyan.cn/';

    public $enableCsrfValidation = false;
    public $data;
    public $userId;
    public $permissions = [
        'index/index',
        'user/login',
    ];

    /**
     * @param \yii\base\Action $action
     * @return array|bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $this->data = [
            'code' => self::API_CODE_FAILURE,
            'msg' => self::API_CODE_FAILURE_MSG
        ];

        $route = $this->module->requestedRoute;
        /*
        if(!in_array($route, $this->permissions)){
            $data = ArrayHelper::merge(Yii::$app->request->get(), Yii::$app->request->post());
            $sid = ArrayHelper::getValue($data, 'sid', null);
            $signData = ScHelper::decode($sid);
            if($signData){
                $id = ArrayHelper::getValue($signData, 'id', 0);
                $cacheUserLoginKey = self::CACHE_USER_LOGIN_KEY . $id;
                $userInfo = Yii::$app->cache->get($cacheUserLoginKey);
                if($userInfo){
                    $this->userId = $userInfo['id'];
                    //Yii::$app->cache->set($cacheUserLoginKey, $userInfo,1800);
                }else{
                    $this->data['msg'] = '请求超时';
                    Yii::$app->response->data = $this->data;
                    return false;
                }
            }else{
                $this->data['msg'] = '非法请求';
                Yii::$app->response->data = $this->data;
                return false;
            }
        }*/

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 加密
     * @param $data
     * @return string
     */
    private function encrypt($data)
    {
        if(!$data || !is_array($data)){
            return null;
        }

        unset($data['r'], $data['sign']);
        ksort($data);
        reset($data);

        $sign = '';
        foreach($data as $k=>$v){
            $sign .= "&" . $k ."=". trim($v);
        }

        return md5(trim($sign, "&").  self::API_SIGN_KEY);
    }
}