<?php
/**
 * Created by PhpStorm.
 * User: M
 * Date: 17/7/5
 * Time: 下午5:21
 */

namespace app\controllers;

use Yii;
use yii\web\Response;
use yii\helpers\ArrayHelper;
use app\components\base\ApiErrorAction;

class Controller extends \yii\web\Controller
{
    const API_CODE_SUCCESS = 10000;
    const API_CODE_FAILURE = 30001;
    const API_CODE_SUCCESS_MSG = '请求成功';
    const API_CODE_FAILURE_MSG = '请求失败';
    const API_SIGN_KEY = 'abc123';

    public $data;
    public $userInfo;
    public $permissions = [
        'user/login'
    ];

    /**
     * @param \yii\base\Action $action
     * @return array|bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $this->data = [
            'code' => self::API_CODE_FAILURE,
            'msg' => self::API_CODE_SUCCESS_MSG
        ];

        $route = $this->module->requestedRoute;
        if(!in_array($route, $this->permissions)){
            $data = ArrayHelper::merge(Yii::$app->request->get(), Yii::$app->request->post());
            $sign = ArrayHelper::getValue($data, 'sign', null);
            $userInfo = Yii::$app->cache->get($sign);
            if($userInfo){
                $this->userInfo = $userInfo;
                Yii::$app->cache->set($sign, $userInfo, 1800);
            }else{
                $this->data['msg'] = '非法请求';
                return $this->data;
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 加密
     * @param $data
     * @return string
     */
    private function encrypt($data)
    {
        if(!$data || !is_array($data)){
            return null;
        }

        unset($data['r'], $data['sign']);
        ksort($data);
        reset($data);

        $sign = '';
        foreach($data as $k=>$v){
            $sign .= "&" . $k ."=". trim($v);
        }

        return md5(trim($sign, "&").  self::API_SIGN_KEY);
    }
}