<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%sms_record}}".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $mobile
 * @property string $content
 * @property integer $send_result
 * @property integer $created_at
 */
class SmsRecord extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%sms_record}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'mobile', 'content'], 'required'],
            [['user_id', 'mobile', 'send_result', 'created_at'], 'integer'],
            [['content'], 'string', 'max' => 30],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => '用户ID',
            'mobile' => '手机号',
            'content' => '发送内容',
            'send_result' => '是否发送',
            'created_at' => '创建结果',
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->created_at = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * 检测是否可以发送
     * @param $id
     * @return bool
     */
    public static function checkSend($id)
    {
        $year = date("Y");
        $month = date("m");
        $day = date("d");
        $startDate = mktime(0, 0, 0, $month, $day, $year);
        $endDate = mktime(23, 59,  59,$month, $day, $year);
        $count = self::find()
            ->where(['user_id' => $id])
            ->andWhere(['between', 'created_at', $startDate, $endDate])
            ->count();
        return $count < 10 ? true : false;
    }
}
