<?php

namespace app\models;

use app\components\helpers\IdentityCardHelper;
use app\components\helpers\SendSmsHelper;
use Yii;
use app\components\helpers\MatchHelper;

/**
 * This is the model class for table "cgt_user".
 *
 * @property integer $id
 * @property string $realname
 * @property integer $mobile
 * @property string $idcard
 * @property string $openid
 * @property integer $is_member
 * @property integer $member_id
 * @property integer $member_time
 * @property integer $is_balance
 * @property integer $balance_id
 * @property integer $balance_amount
 * @property integer $balance_time
 * @property integer $balance_expire_time
 * @property integer $created_at
 * @property integer $verifyCode
 */
class User extends \yii\db\ActiveRecord
{
    const VERIFY_CODE_KEY = 'phone.verify.code.';
    /**
     * 验证码
     * @var
     */
    public $verifyCode;

    public $oldMobile;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['openid'], 'required', 'on' => 'create'],
            [['realname', 'idcard'], 'required', 'on' => ['create', 'info', 'member']],
            [['mobile', 'verifyCode'], 'required', 'on' => ['sendMsm', 'mobile', 'member']],
            [['is_member', 'member_id', 'member_time'], 'required', 'on' => 'member'],
            [['is_member', 'member_id', 'member_time', 'is_balance', 'balance_id', 'balance_time', 'balance_expire_time', 'created_at'], 'integer'],
            [['mobile'], 'integer', 'on' => ['sendMsm', 'mobile', 'member']],
            [['mobile'], 'match', 'pattern' => MatchHelper::$mobile, 'on' => ['sendMsm', 'mobile', 'member'], 'message' => '手机号格式不正确的'],
            [['mobile'], 'compare', 'operator'=>'!==', 'compareAttribute'=>'oldMobile', 'on' => ['sendMsm', 'mobile'], 'message' => '该手机号和原号码一致'],
            [['mobile'], 'unique', 'on' => ['sendMsm', 'mobile', 'member'], 'message' => '该手机号已绑定'],
            [['balance_amount'], 'number'],
            [['realname'], 'string', 'min' => 2, 'max' => 4, 'on' => ['create', 'info', 'member']],
            [['realname'], 'match', 'pattern' => MatchHelper::$chinese, 'message' => '姓名为2-4汉字', 'on' => ['create', 'info', 'member']],
            [[ 'idcard'], 'string', 'min' => 15, 'max' => 18, 'on' => ['create', 'info', 'member']],
            [['idcard'], IdentityCardHelper::className(), 'on' => ['create', 'info', 'member']],
            [['idcard'], 'unique', 'message' => '该身份证已使用',  'on' => ['create', 'info', 'member']],
            [['openid'], 'string', 'max' => 30, 'on' => 'create'],
            [['verifyCode'], 'string', 'min' => 6, 'max'=>6, 'on' => ['mobile', 'member'], 'message' => '验证码输入错误'],
            [['verifyCode'], 'match', 'pattern' => '/^[0-9]{6}$/', 'on' => ['mobile', 'member'], 'message' => '验证码输入错误'],
            ['verifyCode', 'validateVerifyCode', 'on' => ['mobile', 'member']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        return [
            'create'=>[
                'openid', 'created_at'
            ],
            'info' => [
                'realname', 'idcard'
            ],
            'mobile' => [
                'mobile', 'oldMobile', 'verifyCode'
            ],
            'member' => [
                'realname', 'idcard', 'mobile', 'verifyCode', 'is_member', 'member_id', 'member_time'
            ],
            'select' => [
                'id', 'realname', 'mobile', 'idcard', 'openid', 'is_member', 'member_id', 'member_time', 'is_balance', 'balance_id', 'balance_amount', 'balance_time', 'balance_expire_time', 'created_at', 'verifyCode'
            ],
            'sendMsm' => [
                'mobile', 'oldMobile'
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'realname' => '真实姓名',
            'mobile' => '手机号',
            'idcard' => '身份证',
            'openid' => '微信ID',
            'is_member' => '会员（0-否 1-是）',
            'member_id' => '会员等级',
            'member_time' => '会员开通时间',
            'is_balance' => '余额会员（0-否 1-是）',
            'balance_id' => '余额会员等级',
            'balance_amount' => '余额金额',
            'balance_time' => '余额会员开通时间',
            'balance_expire_time' => '余额会员到期时间',
            'created_at' => '创建时间',
            'verifyCode' => '验证码',
        ];
    }

    public function afterFind()
    {
        $this->oldMobile = $this->mobile;
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function validateVerifyCode()
    {
        if (!$this->hasErrors()) {
            $data = $this->checkVerifyCode();
            if ($data['code'] === false) {
                $this->addError('verifyCode', $data['msg']);
            }
        }
    }

    /**
     * 验证手机验证码
     * @return array
     */
    public function checkVerifyCode()
    {
        $data = [
            'code' => false,
            'msg' => '验证码输入错误'
        ];
        if($this->verifyCode){
            $verifyData = Yii::$app->cache->get(self::VERIFY_CODE_KEY . $this->id);
            if($this->verifyCode == $verifyData['verifyCode'] && $this->mobile == $verifyData['mobile']){
                if($verifyData['duration'] >= time()){
                    $data = [
                        'code' => true
                    ];
                }else{
                    $verifyCode['msg'] = '验证码已过期';
                }
            }
        }
        return $data;
    }

    /**
     * 发送验证码
     * @return bool
     */
    public function sendVerifyCode()
    {
        $data = [
            'mobile' => $this->mobile,
            'verifyCode' => rand(100000, 999999),
            'duration' => time() + 600
        ];
        // 发送手机验证码
        //SendSmsHelper::send($this->mobile,'你的短信验证码为:' . $data['verifyCode'] . '。10分钟内有效');
        return Yii::$app->cache->set(self::VERIFY_CODE_KEY . $this->id, $data, 3600 * 6);
    }

    /**
     * @return $this
     */
    public function getMember()
    {
        return $this->hasOne(Member::className(), ['id' => 'member_id'])->select([ 'm.id', 'name']);
    }

    /**
     * @return $this
     */
    public function getMember2()
    {
        return $this->hasOne(Member::className(), ['id' => 'member_id'])->select([ 'mb.id', 'name']);
    }

    /**
     * 获取用户
     * @param $openid
     * @return array|bool
     */
    public static function getUserInfo($openid)
    {
        $user = self::findOne(['openid' => $openid]);
        if(!$user){
            $user = new self();
            $user->openid = $openid;
            $user->created_at = time();
            if(!$user->save()){
                return false;
            }
        }
        $userInfo = [
            'id' =>   $user->id,
            'openid' => $openid
        ];
        return $userInfo;
    }
}
